#########################################################################################
##__________                             ___________     ___.   .__  .__          __   ##
##\______   \_______  _______  ______.__.\__    ___/____ \_ |__ |  | |__| _______/  |_ ##
## |     ___/\_  __ \/  _ \  \/  <   |  |  |    |  \__  \ | __ \|  | |  |/  ___/\   __\##
## |    |     |  | \(  <_> >    < \___  |  |    |   / __ \| \_\ \  |_|  |\___ \  |  |  ##
## |____|     |__|   \____/__/\_ \/ ____|  |____|  (____  /___  /____/__/____  > |__|  ##
##                              \/\/                    \/    \/             \/        ##
#########################################################################################

#|Thanks for choosing ProxyTablist as your solution for Tablist on BungeeCords GLOBAL  |#
#|and GLOBAL_PING - mode. You definitely won't go back from the moment you use this.   |#

#|Please check your config with the YAML-Parser, if you're not sure about the rules you|#
#|have to respect when editing YAML-Files. You can found one of those Parsers online at|#
#|http://yaml-online-parser.appspot.com/ - Just copy and fix the Errors which are shown|#
#|                                     Lots of Fun!                                    |#

#---------------------------------------------------------------------------------------#
#|                                       VERSION                                       |#
#|Don't change the version, or your config will stop working. Just for update-purposes.|#
version: 1

#|                                     AUTOREFRESH                                     |#
#|This Setting does set the amount of Time (in Seconds) for  the auto-refresh of PT.   |#
autorefresh: 60

#|                                      VAULTHOOK                                      |#
#|Shall ProxyTablist query the Permissions from the Server, or use BungeeCord-BuiltIn. |#
vaulthook: false

#|                             PROXYCORE - IMPLEMENTATION                              |#
#|Set this to true or false, depending on your descision. Has to be true for vaulthook.|#
proxycore: false

#|                                    AUTO - UPDATE                                    |#
#|If set to true ProxyCore will be used to autoupdate ProxyTablist. Needs "proxycore". |#
autoupdate: false

#|                                      SORTING                                        |#
#|    The way players get sorted. 0 = unsorted, 1 = alphanumerical, 2 = reversed AN.   |#
sorting: 0
#---------------------------------------------------------------------------------------#

#|You got some variables for usage in the CustomColumns; For example the total Player- |#
#|Count or just from a specific Server. The variables can be found on the SpigotPage.  |#
#|If you need some specific variables just mention them in the diskussion-thread. Thx. |#

#|The following part of the config represents the "CustomColumn"-thing. The Syntax can |#
#|be looked up on the Spigot-Page: http://www.spigotmc.org/resources/proxytablist.50/  |#
#|please respect the rules and backup your config, cuz' if you produce an error it'll  |#
#|                                      get Erased.                                    |#

#---------------------------------------------------------------------------------------#
#|                                    CUSTOM COLUMNS                                   |#
#|Care about the YAML-Formatting, too. Seriously it'll break the whole thing!          |#
customcolumns:
  1:
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  2:
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  3:
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
  - '$player'
#---------------------------------------------------------------------------------------#

#---------------------------------------------------------------------------------------#
#|                                       PREFIXES                                      |#
#|    Here you can add your Servers: 'prefix' to enable a Prefix for that Server.      |#
prefixes:
  server1: '[s1]'
#---------------------------------------------------------------------------------------#

#---------------------------------------------------------------------------------------#
#|                                   THANKS FOR USING                                  |#
#|                                     PROXYTABLIST                                    |#
#|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#